import React from 'react';
import Document, { Head, Main, NextScript } from 'next/document';
import { widthFactory } from '@cmdlucas/react-mediaquery';


/**
 * DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU"RE DOING - IT MAY BREAK SOME FUNCTIONALITIES
 */

function enhanceApp(App, props) {
    return <App {...props} />;
}

class MyDocument extends Document {
    static async getInitialProps(ctx) {

        const globalProps = {
            getWidth: widthFactory(ctx.req["user-agent"])
        }

        const originalRenderPage = ctx.renderPage

        ctx.renderPage = () => originalRenderPage({
            enhanceApp: App => props => enhanceApp(App, { ...props, ...globalProps }),
            enhanceComponent: Component => Component
        })

        const initialProps = await Document.getInitialProps(ctx);

        return { ...initialProps }
    }

    render() {
        return (
            <html>
                <Head></Head>
                <body>
                    <Main />
                    <NextScript />
                </body>
            </html>
        )
    }
}

export default MyDocument